#the connection string for the storage account
azure_storage_connection_string: "DefaultEndpointsProtocol=https;AccountName=anomalydetection9ef6;AccountKey=pv9jYOxTJDDcMSR55I1Y+pdJRAJAOc0nDLRfbw4yiSC3pp8FcAtFFEhcIhnTEZvEZzNGEWf+nyLZ+AStR7uhZA==;EndpointSuffix=core.windows.net"
#the container name for storing the images
frame_container_name: "anomaly-data"
