#the connection string for the storage account
azure_storage_connection_string: "DefaultEndpointsProtocol=https;AccountName=potholedetecti7310831393;AccountKey=XOGMSS/NOqHkIWgxf55XXAKDBLJLfxi2Ut0oZqLfSi0hGt91SCNYkajbFcFFy54eOXG9ZSRvamYiuk/KSukirA==;EndpointSuffix=core.windows.net"
#the container name for storing the images
frame_container_name: "pictures"
